INSERT INTO POAS_EJERECTOR (ID,NOMBRE,DESCRIPCION,CLAVE) VALUES
	 (1,'EDUCACION CON ENFOQUE INTEGRAL','PARA RESPONDER A LAS NECESIDADES DE LA SOCIEDAD Y EL MEDIO AMBIENTE','I'),
	 (2,'INVESTIGACION E INNOVACION','PARA CONTRIBUIR EN LA FORMACION INTEGRAL DE PERSONAS, GENERANDO EFECTOS POSITIVOS A LA DEMANDA SOCIAL Y DEL MEDIO AMBIENTE','II'),
	 (3,'FORMACION INTEGRAL DE PERSONAS','PARA EL DESARROLLO DE SUS DIMENSIONES COGNITIVAS Y PSICOSOCIALES MEJORANDO ASÍ LAS CONDICIONES DE SU ENTORNO.','III'),
	 (4,'INCREMENTO DEL CONOCIMIENTO ACADEMICO DE LA PLANTA DOCENTE','PARA MEJORAR SU DESEMPEÑO Y ASÍ CONTRIBUIR AL LOGRO DE LOS PROPÓSITOS FORMATIVOS.','IV'),
	 (5,'VINCULACION INSTITUCIONAL Y EXTENSION SOCIAL','CON PERTENENCIA Y VISIÓN','V'),
	 (6,'GESTION ADMINISTRATIVA INSTITUCIONAL','PARA LOGRAR EL USO ÓPTIMO DE LOS RECURSOS HUMANOS, MATERIALES, FINANCIEROS Y TECNOLÓGICOS, BRINDANDO ASÍ UN SERVICIO MÁS EFICIENTE A LA COMUNIDAD UNIVERSITARIA.','VI'),
	 (7,'EDUCACION INTEGRAL PARA LA VIDA','PARA PERMITIR A LOS INTEGRANTES DE LA COMUNIDAD HIPÓCRATES HACER FRENTE A LOS RETOS PERSONALES.','VII');
