INSERT INTO POAS_DEPARTAMENTOS (ID,NOMBRE,ID_DIRECCION,CLAVE) VALUES
	 (1,'DIRECCION DE GESTION CALIDAD',1,'RE3'),
	 (2,'TALENTO HUMANO',1,'RE4'),
	 (3,'DIRECCION DE FINANZAS',2,'CG1'),
	 (4,'DIRECCION DE CONTABILIDAD',2,'CG2'),
	 (5,'JEFATURA DE ADQUISICIONES DE BIENES Y SERVICIOS',2,'CG3'),
	 (6,'FACULTAD DE CIENCIAS DE LA SALUD',4,'VA1'),
	 (7,'DIRECCION DE SERVICIOS ESCOLARES',3,'VO4');
